from typing import Dict, List, Union


# ______________________________________________________________________
COUNTRY_RU_EN: Dict[str, str] = {
    "Австралия": "Australia",
    "Австрия": "Austria",
    "Азербайджан": "Azerbaijan",
    "Албания": "Albania",
    "Алжир": "Algeria",
    "Американское Самоа": "American_Samoa",
    "Ангилья": "Anguilla",
    "Ангола": "Angola",
    "Андорра": "Andorra",
    "Антарктида": "Antarctica",
    "Антигуа и Барбуда": "Antigua_and_Barbuda",
    "Аргентина": "Argentina",
    "Армения": "Armenia",
    "Аруба": "Aruba",
    "Афганистан": "Afghanistan",
    "Багамы": "Bahamas",
    "Бангладеш": "Bangladesh",
    "Барбадос": "Barbados",
    "Бахрейн": "Bahrain",
    "Беларусь": "Belarus",
    "Белиз": "Belize",
    "Бельгия": "Belgium",
    "Бенин": "Benin",
    "Бермуды": "Bermuda",
    "Болгария": "Bulgaria",
    "Боливия": "Bolivia",
    "Босния и Герцеговина": "Bosnia_and_Herzegovina",
    "Ботсвана": "Botswana",
    "Бразилия": "Brazil",
    "Британская территория в Индийском океане": "British_Indian_Ocean_Territory",
    "Бруней-Даруссалам": "Brunei_Darussalam",
    "Буркина-Фасо": "Burkina_Faso",
    "Бурунди": "Burundi",
    "Бутан": "Butane",
    "Вануату": "Vanuatu",
    "Венгрия": "Hungary",
    "Венесуэла": "Venezuela",
    "Виргинские острова, Британские": "Virgin_Islands_British",
    "Виргинские острова, США": "Virgin_Islands_USA",
    "Вьетнам": "Vietnam",
    "Габон": "Gabon",
    "Гаити": "Haiti",
    "Гайана": "Guyana",
    "Гамбия": "Gambia",
    "Гана": "Ghana",
    "Гваделупа": "Guadeloupe",
    "Гватемала": "Guatemala",
    "Гвинея": "Guinea",
    "Гвинея-Бисау": "Guinea_Bissau",
    "Германия": "Germany",
    "Гернси": "Guernsey",
    "Гибралтар": "Gibraltar",
    "Гондурас": "Honduras",
    "Гонконг": "Hong_Kong",
    "Гренада": "Grenada",
    "Гренландия": "Greenland",
    "Греция": "Greece",
    "Грузия": "Georgia",
    "Гуам": "Guam",
    "Дания": "Denmark",
    "Джерси": "Jersey",
    "Джибути": "Djibouti",
    "Доминика": "Dominica",
    "Доминиканская Республика": "Dominican_Republic",
    "Египет": "Egypt",
    "Замбия": "Zambia",
    "Западная Сахара": "West_Sahara",
    "Зимбабве": "Zimbabwe",
    "Израиль": "Israel",
    "Индия": "India",
    "Индонезия": "Indonesia",
    "Иордания": "Jordan",
    "Ирак": "Iraq",
    "Иран, Исламская Республика": "Iran_Islamic_Republic",
    "Ирландия": "Ireland",
    "Исландия": "Iceland",
    "Испания": "Spain",
    "Италия": "Italy",
    "Йемен": "Yemen",
    "Кабо-Верде": "Cape_Verde",
    "Казахстан": "Kazakhstan",
    "Камбоджа": "Cambodia",
    "Камерун": "Cameroon",
    "Канада": "Canada",
    "Катар": "Qatar",
    "Кения": "Kenya",
    "Кипр": "Cyprus",
    "Киргизия": "Kyrgyzstan",
    "Кирибати": "Kiribati",
    "Китай": "China",
    "Кокосовые (Килинг) острова": "Cocos_Keeling_Islands",
    "Колумбия": "Colombia",
    "Коморы": "Comoros",
    "Конго": "Congo",
    "Конго, Демократическая Республика": "Congo_Democratic_Republic",
    "Косово": "Kosovo",
    "Коста-Рика": "Costa_Rica",
    "Кот д'Ивуар": "Ivory_Coast",
    "Куба": "Cuba",
    "Кувейт": "Kuwait",
    "Лаос": "Laos",
    "Латвия": "Latvia",
    "Лесото": "Lesotho",
    "Ливан": "Lebanon",
    "Ливийская Арабская Джамахирия": "Libyan_Arab_Jamahiriya",
    "Либерия": "Liberia",
    "Лихтенштейн": "Liechtenstein",
    "Литва": "Lithuania",
    "Люксембург": "Luxembourg",
    "Маврикий": "Mauritius",
    "Мавритания": "Mauritania",
    "Мадагаскар": "Madagascar",
    "Майотта": "Mayotte",
    "Макао": "Macau",
    "Малави": "Malawi",
    "Малайзия": "Malaysia",
    "Мали": "Mali",
    "Малые Тихоокеанские отдаленные острова Соединенных Штатов": "Pacific_Minor_Outlying_Islands_of_the_United_States",
    "Мальдивы": "Maldives",
    "Мальта": "Malta",
    "Марокко": "Morocco",
    "Мартиника": "Martinique",
    "Маршалловы острова": "Marshall_Islands",
    "Мексика": "Mexico",
    "Микронезия, Федеративные Штаты": "Micronesia_Federated_States",
    "Мозамбик": "Mozambique",
    "Молдова, Республика": "Moldova_Republic",
    "Монако": "Monaco",
    "Монголия": "Mongolia",
    "Монтсеррат": "Montserrat",
    "Мьянма": "Myanmar",
    "Намибия": "Namibia",
    "Науру": "Nauru",
    "Непал": "Nepal",
    "Нигер": "Niger",
    "Нигерия": "Nigeria",
    "Нидерландские Антилы": "Netherlands_Antilles",
    "Нидерланды": "Netherlands",
    "Никарагуа": "Nicaragua",
    "Ниуэ": "Niue",
    "Новая Зеландия": "New_Zealand",
    "Новая Каледония": "New_Caledonia",
    "Норвегия": "Norway",
    "Объединенные Арабские Эмираты": "United_Arab_Emirates",
    "Оман": "Oman",
    "Остров Буве": "Bouvet_Island",
    "Остров Клиппертон": "Clipperton_Island",
    "Остров Мэн": "Isle_Of_Man",
    "Остров Норфолк": "Norfolk_Island",
    "Остров Рождества": "Christmas_Island",
    "Остров Святого Мартина": "Saint_Martins_Island",
    "Остров Херд и острова Макдональд": "Heard_Island_and_McDonald_Islands",
    "Острова Кайман": "Cayman_Islands",
    "Острова Кука": "Cook_Islands",
    "Острова Теркс и Кайкос": "Turks_and_Caicos_Islands",
    "Пакистан": "Pakistan",
    "Палау": "Palau",
    "Палестинская территория, оккупированная": "Palestinian_Territory_Occupied",
    "Панама": "Panama",
    "Папский Престол (Государство — город Ватикан)": "Pontifical_See_State_Vatican_city",
    "Папуа-Новая Гвинея": "Papua_New_Guinea",
    "Парагвай": "Paraguay",
    "Перу": "Peru",
    "Питкерн": "Pitcairn",
    "Польша": "Poland",
    "Португалия": "Portugal",
    "Пуэрто-Рико": "Puerto_Rico",
    "Республика Македония": "Republic_of_Macedonia",
    "Реюньон": "Reunion",
    "Россия": "Russia",
    "Руанда": "Rwanda",
    "Румыния": "Romania",
    "Самоа": "Samoa",
    "Сан-Марино": "San_Marino",
    "Сан-Томе и Принсипи": "Sao_Tome_and_Principe",
    "Саудовская Аравия": "Saudi_Arabia",
    "Свазиленд": "Swaziland",
    "Святая Елена": "Saint_Elena",
    "Северная Корея": "North_Korea",
    "Северные Марианские острова": "Northern_Mariana_Islands",
    "Сен-Бартельми": "Saint_Barthelemy",
    "Сен-Пьер и Микелон": "Saint_Pierre_and_Miquelon",
    "Сенегал": "Senegal",
    "Сент-Винсент и Гренадины": "Saint_Vincent_and_the_Grenadines",
    "Сент-Люсия": "Saint_Lucia",
    "Сент-Китс и Невис": "Saint_Kitts_and_Nevis",
    "Сербия": "Serbia",
    "Сейшелы": "Seychelles",
    "Сингапур": "Singapore",
    "Сирийская Арабская Республика": "Syrian_Arab_Republic",
    "Словакия": "Slovakia",
    "Словения": "Slovenia",
    "Соединенное Королевство": "United_Kingdom",
    "Соединенные Штаты": "United_States",
    "Соломоновы острова": "Solomon_islands",
    "Сомали": "Somalia",
    "Судан": "Sudan",
    "Суринам": "Suriname",
    "Сьерра-Леоне": "Sierra_Leone",
    "Таджикистан": "Tajikistan",
    "Таиланд": "Thailand",
    "Танзания, Объединенная Республика": "Tanzania_United_Republic",
    "Тайвань (Китай)": "Taiwan_China",
    "Тимор-Лесте": "Timor_Leste",
    "Того": "Togo",
    "Токелау": "Tokelau",
    "Тонга": "Tonga",
    "Тринидад и Тобаго": "Trinidad_and_Tobago",
    "Тувалу": "Tuvalu",
    "Тунис": "Tunisia",
    "Туркмения": "Turkmenistan",
    "Турция": "Türkiye",
    "Уганда": "Uganda",
    "Узбекистан": "Uzbekistan",
    "Украина": "Ukraine",
    "Уоллис и Футуна": "Wallis_and_Futuna",
    "Уругвай": "Uruguay",
    "Фарерские острова": "Faroe_islands",
    "Фиджи": "Fiji",
    "Филиппины": "Philippines",
    "Финляндия": "Finland",
    "Фолклендские острова (Мальвинские)": "Falkland_Islands_Malvinas",
    "Франция": "France",
    "Французская Гвиана": "French_Guiana",
    "Французская Полинезия": "French_polynesia",
    "Французские Южные территории": "French_Southern_Territories",
    "Хорватия": "Croatia",
    "Центрально-Африканская Республика": "Central_African_Republic",
    "Чад": "Chad",
    "Черногория": "Montenegro",
    "Чешская Республика": "Czech_Republic",
    "Чили": "Chile",
    "Швейцария": "Switzerland",
    "Швеция": "Sweden",
    "Шпицберген и Ян Майен": "Svalbard_and_Jan_Mayen",
    "Шри-Ланка": "Sri_Lanka",
    "Эквадор": "Ecuador",
    "Экваториальная Гвинея": "Equatorial_Guinea",
    "Эландские острова": "Eland_Islands",
    "Эль-Сальвадор": "El_Salvador",
    "Эритрея": "Eritrea",
    "Эстония": "Estonia",
    "Эфиопия": "Ethiopia",
    "Южная Африка": "South_Africa",
    "Южная Джорджия и Южные Сандвичевы острова": "South_Georgia_and_the_South_Sandwich_Islands",
    "Южная Корея": "South_Korea",
    "Ямайка": "Jamaica",
    "Япония": "Japan",
}
# ______________________________________________________________________

# ______________________________________________________________________
COUNTRY_MAPPING: Dict[str, int] = {
    "Australia": 1,
    "Austria": 2,
    "Azerbaijan": 3,
    "Albania": 4,
    "Algeria": 5,
    "American_Samoa": 6,
    "Anguilla": 7,
    "Angola": 8,
    "Andorra": 9,
    "Antarctica": 10,
    "Antigua_and_Barbuda": 11,
    "Argentina": 12,
    "Armenia": 13,
    "Aruba": 14,
    "Afghanistan": 15,
    "Bahamas": 16,
    "Bangladesh": 17,
    "Barbados": 18,
    "Bahrain": 19,
    "Belarus": 20,
    "Belize": 21,
    "Belgium": 22,
    "Benin": 23,
    "Bermuda": 24,
    "Bulgaria": 25,
    "Bolivia": 26,
    "Bosnia_and_Herzegovina": 27,
    "Botswana": 28,
    "Brazil": 29,
    "British_Indian_Ocean_Territory": 30,
    "Brunei_Darussalam": 31,
    "Burkina_Faso": 32,
    "Burundi": 33,
    "Butane": 34,
    "Vanuatu": 35,
    "Hungary": 36,
    "Venezuela": 37,
    "Virgin_Islands_British": 38,
    "Virgin_Islands_USA": 39,
    "Vietnam": 40,
    "Gabon": 41,
    "Haiti": 42,
    "Guyana": 43,
    "Gambia": 44,
    "Ghana": 45,
    "Guadeloupe": 46,
    "Guatemala": 47,
    "Guinea": 48,
    "Guinea_Bissau": 49,
    "Germany": 50,
    "Guernsey": 51,
    "Gibraltar": 52,
    "Honduras": 53,
    "Hong_Kong": 54,
    "Grenada": 55,
    "Greenland": 56,
    "Greece": 57,
    "Georgia": 58,
    "Guam": 59,
    "Denmark": 60,
    "Jersey": 61,
    "Djibouti": 62,
    "Dominica": 63,
    "Dominican_Republic": 64,
    "Egypt": 65,
    "Zambia": 66,
    "West_Sahara": 67,
    "Zimbabwe": 68,
    "Israel": 69,
    "India": 70,
    "Indonesia": 71,
    "Jordan": 72,
    "Iraq": 73,
    "Iran_Islamic_Republic": 74,
    "Ireland": 75,
    "Iceland": 76,
    "Spain": 77,
    "Italy": 78,
    "Yemen": 79,
    "Cape_Verde": 80,
    "Kazakhstan": 81,
    "Cambodia": 82,
    "Cameroon": 83,
    "Canada": 84,
    "Qatar": 85,
    "Kenya": 86,
    "Cyprus": 87,
    "Kyrgyzstan": 88,
    "Kiribati": 89,
    "China": 90,
    "Cocos_Keeling_Islands": 91,
    "Colombia": 92,
    "Comoros": 93,
    "Congo": 94,
    "Congo_Democratic_Republic": 95,
    "Kosovo": 96,
    "Costa_Rica": 97,
    "Ivory_Coast": 98,
    "Cuba": 99,
    "Kuwait": 100,
    "Laos": 101,
    "Latvia": 102,
    "Lesotho": 103,
    "Lebanon": 104,
    "Libyan_Arab_Jamahiriya": 105,
    "Liberia": 106,
    "Liechtenstein": 107,
    "Lithuania": 108,
    "Luxembourg": 109,
    "Mauritius": 110,
    "Mauritania": 111,
    "Madagascar": 112,
    "Mayotte": 113,
    "Macau": 114,
    "Malawi": 115,
    "Malaysia": 116,
    "Mali": 117,
    "Pacific_Minor_Outlying_Islands_of_the_United_States": 118,
    "Maldives": 119,
    "Malta": 120,
    "Morocco": 121,
    "Martinique": 122,
    "Marshall_Islands": 123,
    "Mexico": 124,
    "Micronesia_Federated_States": 125,
    "Mozambique": 126,
    "Moldova_Republic": 127,
    "Monaco": 128,
    "Mongolia": 129,
    "Montserrat": 130,
    "Myanmar": 131,
    "Namibia": 132,
    "Nauru": 133,
    "Nepal": 134,
    "Niger": 135,
    "Nigeria": 136,
    "Netherlands_Antilles": 137,
    "Netherlands": 138,
    "Nicaragua": 139,
    "Niue": 140,
    "New_Zealand": 141,
    "New_Caledonia": 142,
    "Norway": 143,
    "United_Arab_Emirates": 144,
    "Oman": 145,
    "Bouvet_Island": 146,
    "Clipperton_Island": 147,
    "Isle_Of_Man": 148,
    "Norfolk_Island": 149,
    "Christmas_Island": 150,
    "Saint_Martins_Island": 151,
    "Heard_Island_and_McDonald_Islands": 152,
    "Cayman_Islands": 153,
    "Cook_Islands": 154,
    "Turks_and_Caicos_Islands": 155,
    "Pakistan": 156,
    "Palau": 157,
    "Palestinian_Territory_Occupied": 158,
    "Panama": 159,
    "Pontifical_See_State_Vatican_city": 160,
    "Papua_New_Guinea": 161,
    "Paraguay": 162,
    "Peru": 163,
    "Pitcairn": 164,
    "Poland": 165,
    "Portugal": 166,
    "Puerto_Rico": 167,
    "Republic_of_Macedonia": 168,
    "Reunion": 169,
    "Russia": 170,
    "Rwanda": 171,
    "Romania": 172,
    "Samoa": 173,
    "San_Marino": 174,
    "Sao_Tome_and_Principe": 175,
    "Saudi_Arabia": 176,
    "Swaziland": 177,
    "Saint_Elena": 178,
    "North_Korea": 179,
    "Northern_Mariana_Islands": 180,
    "Saint_Barthelemy": 181,
    "Saint_Pierre_and_Miquelon": 182,
    "Senegal": 183,
    "Saint_Vincent_and_the_Grenadines": 184,
    "Saint_Lucia": 185,
    "Saint_Kitts_and_Nevis": 186,
    "Serbia": 187,
    "Seychelles": 188,
    "Singapore": 189,
    "Syrian_Arab_Republic": 190,
    "Slovakia": 191,
    "Slovenia": 192,
    "United_Kingdom": 193,
    "United_States": 194,
    "Solomon_islands": 195,
    "Somalia": 196,
    "Sudan": 197,
    "Suriname": 198,
    "Sierra_Leone": 199,
    "Tajikistan": 200,
    "Thailand": 201,
    "Tanzania_United_Republic": 202,
    "Taiwan_China": 203,
    "Timor_Leste": 204,
    "Togo": 205,
    "Tokelau": 206,
    "Tonga": 207,
    "Trinidad_and_Tobago": 208,
    "Tuvalu": 209,
    "Tunisia": 210,
    "Turkmenistan": 211,
    "Türkiye": 212,
    "Uganda": 213,
    "Uzbekistan": 214,
    "Ukraine": 215,
    "Wallis_and_Futuna": 216,
    "Uruguay": 217,
    "Faroe_islands": 218,
    "Fiji": 219,
    "Philippines": 220,
    "Finland": 221,
    "Falkland_Islands_Malvinas": 222,
    "France": 223,
    "French_Guiana": 224,
    "French_polynesia": 225,
    "French_Southern_Territories": 226,
    "Croatia": 227,
    "Central_African_Republic": 228,
    "Chad": 229,
    "Montenegro": 230,
    "Czech_Republic": 231,
    "Chile": 232,
    "Switzerland": 233,
    "Sweden": 234,
    "Svalbard_and_Jan_Mayen": 235,
    "Sri_Lanka": 236,
    "Ecuador": 237,
    "Equatorial_Guinea": 238,
    "Eland_Islands": 239,
    "El_Salvador": 240,
    "Eritrea": 241,
    "Estonia": 242,
    "Ethiopia": 243,
    "South_Africa": 244,
    "South_Georgia_and_the_South_Sandwich_Islands": 245,
    "South_Korea": 246,
    "Jamaica": 247,
    "Japan": 248,
}

COUNTRY_FOR_KEYS: List[int] = list(range(1, 249))
# ______________________________________________________________________

# ______________________________________________________________________
CURRENCY_MAPPING: Dict[str, int] = {
    "AUD": 1,
    "EUR": 2,
    "AZN": 3,
    "ALL": 4,
    "DZD": 5,
    "USD": 6,
    "XCD": 7,
    "AOA": 8,
    "SYP": 9,
    "ARS": 10,
    "AMD": 11,
    "AWG": 12,
    "AFN": 13,
    "BSD": 14,
    "BDT": 15,
    "BBD": 16,
    "BHD": 17,
    "BYR": 18,
    "BZD": 19,
    "XOF": 20,
    "BMD": 21,
    "BGN": 22,
    "BOB": 23,
    "BOV": 24,
    "BAM": 25,
    "BWP": 26,
    "BRL": 27,
    "BND": 28,
    "BIF": 29,
    "BTN": 30,
    "INR": 31,
    "VUV": 32,
    "GBP": 33,
    "HUF": 34,
    "VEF": 35,
    "VND": 36,
    "GMD": 37,
    "XAF": 38,
    "HTG": 39,
    "GYD": 40,
    "GHS": 41,
    "GTQ": 42,
    "GNF": 43,
    "GIP": 44,
    "HNL": 45,
    "HKD": 46,
    "DKK": 47,
    "GEL": 48,
    "DJF": 49,
    "DOP": 50,
    "EGP": 51,
    "ZMW": 52,
    "MAD": 53,
    "ZWL": 54,
    "ILS": 55,
    "IDR": 56,
    "JOD": 57,
    "IQD": 58,
    "IRR": 59,
    "ISK": 60,
    "YER": 61,
    "CVE": 62,
    "KZT": 63,
    "KYD": 64,
    "KHR": 65,
    "CAD": 66,
    "QAR": 67,
    "KES": 68,
    "CNY": 69,
    "COP": 70,
    "COU": 71,
    "KMF": 72,
    "CDF": 73,
    "KPW": 74,
    "CRC": 75,
    "CUC": 76,
    "CUP": 77,
    "KWD": 78,
    "KGS": 79,
    "ANG": 80,
    "LAK": 81,
    "LSL": 82,
    "ZAR": 83,
    "LRD": 84,
    "LBP": 85,
    "LYD": 86,
    "CHF": 87,
    "MUR": 88,
    "MRO": 89,
    "MGA": 90,
    "MOP": 91,
    "MKD": 92,
    "MWK": 93,
    "MYR": 94,
    "FKP": 95,
    "MVR": 96,
    "XDR": 97,
    "MXN": 98,
    "MXV": 99,
    "MZN": 100,
    "MDL": 101,
    "MNT": 102,
    "MMK": 103,
    "NAD": 104,
    "NPR": 105,
    "NGN": 106,
    "NIO": 107,
    "NZD": 108,
    "XPF": 109,
    "NOK": 110,
    "AED": 111,
    "OMR": 112,
    "SHP": 113,
    "PKR": 114,
    "PAB": 115,
    "PGK": 116,
    "PYG": 117,
    "PEN": 118,
    "PLN": 119,
    "RUB": 120,
    "RWF": 121,
    "RON": 122,
    "SVC": 123,
    "WST": 124,
    "STD": 125,
    "SAR": 126,
    "SZL": 127,
    "SCR": 128,
    "RSD": 129,
    "SGD": 130,
    "XSU": 131,
    "SBD": 132,
    "SOS": 133,
    "XUA": 134,
    "SDG": 135,
    "SRD": 136,
    "SLL": 137,
    "TJS": 138,
    "THB": 139,
    "TWD": 140,
    "TZS": 141,
    "TOP": 142,
    "TTD": 143,
    "TND": 144,
    "TMT": 145,
    "TRY": 146,
    "UGX": 147,
    "UZS": 148,
    "UAH": 149,
    "UYI": 150,
    "UYU": 151,
    "FJD": 152,
    "PHP": 153,
    "HRK": 154,
    "CZK": 155,
    "CLF": 156,
    "CLP": 157,
    "CHE": 158,
    "CHW": 159,
    "SEK": 160,
    "LKR": 161,
    "ERN": 162,
    "ETB": 163,
    "KRW": 164,
    "SSP": 165,
    "JMD": 166,
    "JPY": 167,
}

CURRENCY_FOR_KEYS: List[int] = list(range(1, 168))
# ______________________________________________________________________

# ______________________________________________________________________
FINANCIAL_STATEMENT_ROW_TYPE_MAPPING: Dict[str, int] = {
    "Balance sheet": 1,
    "Profit and loss": 2,
    "Cash flow statement": 3,
}

FINANCIAL_STATEMENT_ROW_TYPE_FOR_KEYS: List[int] = list(range(1, 4))
# ______________________________________________________________________

# ______________________________________________________________________
FINANCIAL_STATEMENT_PERIOD_TYPE_MAPPING: Dict[str, int] = {
    "Annual": 1,
    "Quarterly": 2,
    "Semi-annual": 3,
    "Nine month": 4,
}

FINANCIAL_STATEMENT_PERIOD_TYPE_FOR_KEYS: List[int] = list(range(1, 5))
# ______________________________________________________________________

# ______________________________________________________________________
STATUS_INFORMATION_MAPPING: Dict[str, int] = {
    "Actual": 1,
    "Irrelevant": 2,
    "Needing verification": 3,
}

STATUS_INFORMATION_FOR_KEYS: List[int] = list(range(1, 4))
# ______________________________________________________________________

# ______________________________________________________________________
TRACKED_TABLE_MAPPING: Dict[str, int] = {
    "company": 1,
    "capital": 2,
    "classifier": 3,
    "financial_statement": 4,
    "financial_statement_row": 5,
    "person": 6,
    "manager": 7,
    "shareholder": 8,
    "contact": 9,
    "address": 10,
    "activity": 11,
    "license": 12,
    "sanctions": 13,
    "company_branch": 14,
}

TRACKED_TABLE_FOR_KEYS: List[int] = list(range(1, 15))
# ______________________________________________________________________

# ______________________________________________________________________
CONTACT_TYPE_MAPPING: Dict[str, int] = {
    "Phone": 1,
    "Fax": 2,
    "Email": 3,
    "Site": 4,
    "Social network": 5,
}

CONTACT_TYPE_FOR_KEYS: List[int] = list(range(1, 6))
# ______________________________________________________________________
DATA_TYPE_MAPPING: Dict[str, int] = {
    "str": 1,
    "int": 2,
    "float": 3,
    "date": 4,
    "datetime": 5,
    "null": 6,
    "decimal": 7,
    "list": 8,
}

DATA_TYPE_FOR_KEYS: List[int] = list(range(1, 7))
# ______________________________________________________________________

# ______________________________________________________________________
TABLE_UPDATING_KEYS: Dict[str, Dict[str, Union[str, Union[List[str], bool]]]] = {
    "company_branch": {
        "identification_keys": [
            "main_identifier",
            "sub_identifier",
        ],
        "needs_updating_data":True,
        "needs_updating_status": True,
    },
    "activity": {
        "identification_keys": [
                "is_main",
                "code",
            ],
        "needs_updating_data":True,
        "needs_updating_status": True,
    },
    "capital": {
        "identification_keys": [
                "type",
                "value",
            ],
        "needs_updating_data":True,
        "needs_updating_status": True,
    },
    "classifier": {
        "identification_keys": [
                "name",
                "value",
            ],
        "needs_updating_data":True,
        "needs_updating_status": True,
    },
    "license": {
        "identification_keys": [
                "license_identifier",
                "license_body",
            ],
        "needs_updating_data":True,
        "needs_updating_status": True,
    },
    "financial_tatement": {
        "identification_keys": [
                "period_type_id",
                "date",
            ],
        "needs_updating_data":True,
        "needs_updating_status": False,
    },
    "financial_statement_row": {
        "identification_keys": [
                "name",
                "status_info_id",
                "value",
            ],
        "needs_updating_data":True,
        "needs_updating_status": True,
    },
    "contact": {
        "identification_keys": [
                "contact_type_id",
                "value",
            ],
        "needs_updating_data":True,
        "needs_updating_status": True,
    },
    "address": {
        "identification_keys": [
                "address_type",
                "full_address",
            ],
        "needs_updating_data":True,
        "needs_updating_status": True,
    },
    "sanction": {
        "identification_keys": [
                "country_id",
                "description",
            ],
        "needs_updating_data":True,
        "needs_updating_status": True,
    },
    "event": {
        "identification_keys": [
                "date",
                "description",
            ],
        "needs_updating_data":False,
        "needs_updating_status": False,
    },
    "manager": {
        "identification_keys": [
                "person_id",
                "company_id",
            ],
        "needs_updating_data": True,
        "needs_updating_status": True,
    },
    "shareholder": {
        "identification_keys": [
                "company_shareholder_id",
                "person_shareholder_id",
                "company_share_id",
            ],
        "needs_updating_data": True,
        "needs_updating_status": True,
    },
    
}
# ______________________________________________________________________

# ______________________________________________________________________
PARTICIPANT_TYPE_MAPPING: Dict[str, int] = {
    "Plaintiff": 1,
    "Defendant": 2,
}

PARTICIPANT_TYPE_FOR_KEYS: List[int] = list(range(1, 3))
# ______________________________________________________________________
