/**
 * «Моя повестка» — the personal, cross-cutting queue. /limits and /requests
 * stay the domain views; this one answers a different question: what do *I*
 * owe right now, whatever object it hangs off.
 *
 * Rows are generated by the database (migration 0024) and close themselves
 * when their object moves on, so there is no bulk-complete here — only
 * bulk-OPEN, which is the action a queue actually needs.
 */

import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { useTranslation } from 'react-i18next'

import {
  Badge,
  Button,
  Card,
  EmptyState,
  Field,
  PageHeader,
  Select,
  Spinner,
} from '../../components/ui'
import { EM_DASH, formatMoment } from '../../lib/format'
import { subjectFor, useAgendaTasks, useCompleteTask, useTaskSubjects } from './api'
import {
  applyFilters,
  canCompleteByHand,
  groupTasks,
  isOverdue,
  NO_FILTERS,
  OBJECT_FILTERS,
  taskLink,
} from './catalogue'
import type { AgendaFilters, AgendaGroup } from './catalogue'
import { TASK_TYPES } from './types'
import type { Task, TaskType } from './types'

const GROUP_TONE: Record<AgendaGroup, string> = {
  overdue: 'border-neg-500/40 bg-neg-50',
  urgent: 'border-warn-500/40 bg-warn-50',
  high: 'border-slate-200 bg-white',
  normal: 'border-slate-200 bg-white',
}

export function AgendaPage() {
  const { t, i18n } = useTranslation()
  const { data: tasks, isLoading, isError, dataUpdatedAt } = useAgendaTasks()
  const { data: subjects } = useTaskSubjects(tasks)
  const complete = useCompleteTask()

  const [filters, setFilters] = useState<AgendaFilters>(NO_FILTERS)
  const [selected, setSelected] = useState<ReadonlySet<string>>(new Set())
  const [actionError, setActionError] = useState<string | null>(null)

  // One clock for the whole board, taken when the rows were fetched, so a
  // task cannot be overdue in its badge and on time in its group.
  const now = useMemo(() => new Date(dataUpdatedAt || Date.now()), [dataUpdatedAt])

  const visible = useMemo(() => applyFilters(tasks ?? [], filters), [tasks, filters])
  const sections = useMemo(() => groupTasks(visible, now), [visible, now])

  const toggle = (id: string) => {
    setSelected((current) => {
      const next = new Set(current)
      if (next.has(id)) next.delete(id)
      else next.add(id)
      return next
    })
  }

  const selectedLinks = visible
    .filter((task) => selected.has(task.id))
    .map(taskLink)
    .filter((href): href is string => href !== null)

  const openSelected = () => {
    for (const href of selectedLinks) {
      window.open(href, '_blank', 'noopener')
    }
  }

  const runComplete = async (task: Task) => {
    setActionError(null)
    try {
      await complete.mutateAsync(task.id)
      setSelected((current) => {
        const next = new Set(current)
        next.delete(task.id)
        return next
      })
    } catch {
      setActionError(t('agenda.completeFailed'))
    }
  }

  if (isLoading) return <Spinner label={t('common.loading')} />

  return (
    <div>
      <PageHeader
        title={t('agenda.title')}
        subtitle={t('agenda.subtitle')}
        actions={
          <Button
            variant="secondary"
            disabled={selectedLinks.length === 0}
            onClick={openSelected}
            title={t('agenda.openSelectedHint')}
          >
            {t('agenda.openSelected', { count: selectedLinks.length })}
          </Button>
        }
      />

      {isError && (
        <div
          className="mb-4 rounded-md border border-neg-500/30 bg-neg-50 px-4 py-2.5 text-[13px] text-neg-500"
          role="alert"
        >
          {t('agenda.loadFailed')}
        </div>
      )}
      {actionError && (
        <div
          className="mb-4 rounded-md border border-neg-500/30 bg-neg-50 px-4 py-2.5 text-[13px] text-neg-500"
          role="alert"
        >
          {actionError}
        </div>
      )}

      <Card className="mb-5 flex flex-wrap items-end gap-3 p-4">
        <Field label={t('agenda.filters.taskType')} className="min-w-56">
          <Select
            value={filters.taskType}
            onChange={(e) =>
              setFilters((f) => ({ ...f, taskType: e.target.value as TaskType | '' }))
            }
          >
            <option value="">{t('agenda.filters.anyType')}</option>
            {TASK_TYPES.map((type) => (
              <option key={type} value={type}>
                {t(`agenda.taskTypes.${type}`)}
              </option>
            ))}
          </Select>
        </Field>
        <Field label={t('agenda.filters.objectType')} className="min-w-56">
          <Select
            value={filters.objectType}
            onChange={(e) =>
              setFilters((f) => ({
                ...f,
                objectType: e.target.value as AgendaFilters['objectType'],
              }))
            }
          >
            <option value="">{t('agenda.filters.anyObject')}</option>
            {OBJECT_FILTERS.map((kind) => (
              <option key={kind} value={kind}>
                {t(`agenda.objectTypes.${kind}`)}
              </option>
            ))}
          </Select>
        </Field>
        {(filters.taskType || filters.objectType) && (
          <Button variant="ghost" onClick={() => setFilters(NO_FILTERS)}>
            {t('agenda.filters.reset')}
          </Button>
        )}
      </Card>

      {sections.length === 0 ? (
        <EmptyState
          title={
            tasks?.length ? t('agenda.empty.filtered') : t('agenda.empty.title')
          }
          hint={tasks?.length ? t('agenda.empty.filteredHint') : t('agenda.empty.hint')}
        />
      ) : (
        <div className="flex flex-col gap-5">
          {sections.map((section) => (
            <section key={section.group}>
              <h2 className="mb-2 flex items-center gap-2 text-sm font-semibold text-slate-700">
                {t(`agenda.groups.${section.group}`)}
                <span className="num text-xs font-normal text-slate-400">
                  {section.tasks.length}
                </span>
              </h2>
              <div className="flex flex-col gap-2">
                {section.tasks.map((task) => (
                  <TaskRow
                    key={task.id}
                    task={task}
                    tone={GROUP_TONE[section.group]}
                    subject={subjectFor(task, subjects)}
                    locale={i18n.language}
                    now={now}
                    checked={selected.has(task.id)}
                    onToggle={() => toggle(task.id)}
                    onComplete={() => void runComplete(task)}
                    completing={complete.isPending}
                  />
                ))}
              </div>
            </section>
          ))}
        </div>
      )}
    </div>
  )
}

interface TaskRowProps {
  task: Task
  tone: string
  subject: string | null
  locale: string
  now: Date
  checked: boolean
  onToggle: () => void
  onComplete: () => void
  completing: boolean
}

function TaskRow({
  task,
  tone,
  subject,
  locale,
  now,
  checked,
  onToggle,
  onComplete,
  completing,
}: TaskRowProps) {
  const { t } = useTranslation()
  const href = taskLink(task)
  const overdue = isOverdue(task, now)

  return (
    <div className={`flex items-start gap-3 rounded-lg border px-4 py-3 ${tone}`}>
      <input
        type="checkbox"
        checked={checked}
        onChange={onToggle}
        disabled={!href}
        aria-label={t('agenda.selectRow')}
        className="mt-1 size-4 shrink-0 rounded border-slate-300 accent-accent-600 disabled:opacity-40"
      />
      <div className="min-w-0 flex-1">
        <p className="text-sm font-medium text-slate-900">
          {t(task.title_key, { ...task.params, subject: subject ?? EM_DASH })}
        </p>
        <p className="mt-0.5 flex flex-wrap items-center gap-x-2 gap-y-1 text-[13px] text-slate-500">
          <Badge tone="neutral">{t(`agenda.taskTypes.${task.task_type}`)}</Badge>
          {subject && (
            <span className="truncate">
              {href ? (
                <Link to={href} className="text-accent-700 hover:underline">
                  {subject}
                </Link>
              ) : (
                subject
              )}
            </span>
          )}
          {task.due_at && (
            <span className={overdue ? 'font-medium text-neg-500' : undefined}>
              {t(overdue ? 'agenda.overdueSince' : 'agenda.dueBy', {
                moment: formatMoment(task.due_at, locale),
              })}
            </span>
          )}
        </p>
      </div>
      <div className="flex shrink-0 items-center gap-2">
        {canCompleteByHand(task.task_type) && (
          <Button variant="secondary" size="sm" disabled={completing} onClick={onComplete}>
            {t('agenda.markDone')}
          </Button>
        )}
        {href && (
          <Link
            to={href}
            className="rounded-md border border-slate-300 bg-white px-2.5 py-1 text-[13px] font-medium text-slate-700 shadow-sm hover:bg-slate-50"
          >
            {t('agenda.open')}
          </Link>
        )}
      </div>
    </div>
  )
}
