-- 0002_reference_tables.sql
-- What: reference tables tci.countries / tci.industries / tci.currencies with trilingual
--       names (en/ru/uz) + seed data (full ISO 3166-1 country list, core currencies,
--       starter industry list).
-- Why:  buyers, policies and declarations all reference countries/industries/currencies;
--       amounts are always stored with a currency code (UZS/USD/EUR at minimum).

create table tci.countries (
  code    char(2) primary key,   -- ISO 3166-1 alpha-2
  name_en text not null,
  name_ru text not null,
  name_uz text not null
);

create table tci.industries (
  code    text primary key,
  name_en text not null,
  name_ru text not null,
  name_uz text not null
);

create table tci.currencies (
  code    char(3) primary key,   -- ISO 4217
  name_en text not null,
  name_ru text not null,
  name_uz text not null
);

comment on table tci.countries  is 'ISO 3166-1 country reference, trilingual names.';
comment on table tci.industries is 'Industry sectors for buyer classification, trilingual names.';
comment on table tci.currencies is 'ISO 4217 currencies used in policies and limits.';

alter table tci.countries  enable row level security;
alter table tci.industries enable row level security;
alter table tci.currencies enable row level security;

-- Read: any authenticated user. Write: admin only.
create policy "countries: authenticated read"  on tci.countries  for select to authenticated using (true);
create policy "industries: authenticated read" on tci.industries for select to authenticated using (true);
create policy "currencies: authenticated read" on tci.currencies for select to authenticated using (true);

create policy "countries: admin write" on tci.countries for all to authenticated
  using (tci.current_user_role() = 'admin') with check (tci.current_user_role() = 'admin');
create policy "industries: admin write" on tci.industries for all to authenticated
  using (tci.current_user_role() = 'admin') with check (tci.current_user_role() = 'admin');
create policy "currencies: admin write" on tci.currencies for all to authenticated
  using (tci.current_user_role() = 'admin') with check (tci.current_user_role() = 'admin');

grant select, insert, update, delete on tci.countries, tci.industries, tci.currencies to authenticated;
grant all on tci.countries, tci.industries, tci.currencies to service_role;

-- ---------------------------------------------------------------------------
-- Seed: currencies
-- ---------------------------------------------------------------------------
insert into tci.currencies (code, name_en, name_ru, name_uz) values
  ('UZS', 'Uzbek som',            'Узбекский сум',        'O''zbek so''mi'),
  ('USD', 'US dollar',            'Доллар США',           'AQSh dollari'),
  ('EUR', 'Euro',                 'Евро',                 'Yevro'),
  ('GBP', 'Pound sterling',       'Фунт стерлингов',      'Funt sterling'),
  ('CHF', 'Swiss franc',          'Швейцарский франк',    'Shveytsariya franki'),
  ('JPY', 'Japanese yen',         'Японская иена',        'Yaponiya iyenasi'),
  ('CNY', 'Chinese yuan',         'Китайский юань',       'Xitoy yuani'),
  ('RUB', 'Russian ruble',        'Российский рубль',     'Rossiya rubli'),
  ('KZT', 'Kazakhstani tenge',    'Казахстанский тенге',  'Qozog''iston tengesi'),
  ('TRY', 'Turkish lira',         'Турецкая лира',        'Turk lirasi'),
  ('AED', 'UAE dirham',           'Дирхам ОАЭ',           'BAA dirhami'),
  ('KRW', 'South Korean won',     'Южнокорейская вона',   'Janubiy Koreya voni');

-- ---------------------------------------------------------------------------
-- Seed: industries (starter list, ~20 common sectors)
-- ---------------------------------------------------------------------------
insert into tci.industries (code, name_en, name_ru, name_uz) values
  ('AGRI',  'Agriculture & farming',            'Сельское хозяйство',                 'Qishloq xo''jaligi'),
  ('FOOD',  'Food & beverages',                 'Продукты питания и напитки',         'Oziq-ovqat va ichimliklar'),
  ('TEXT',  'Textiles & apparel',               'Текстиль и одежда',                  'To''qimachilik va kiyim-kechak'),
  ('CHEM',  'Chemicals',                        'Химическая промышленность',          'Kimyo sanoati'),
  ('PHAR',  'Pharmaceuticals & healthcare',     'Фармацевтика и здравоохранение',     'Farmatsevtika va sog''liqni saqlash'),
  ('METL',  'Metals & mining',                  'Металлургия и горнодобыча',          'Metallurgiya va kon sanoati'),
  ('MACH',  'Machinery & equipment',            'Машиностроение и оборудование',      'Mashinasozlik va uskunalar'),
  ('ELEC',  'Electronics & electrical',         'Электроника и электротехника',       'Elektronika va elektrotexnika'),
  ('AUTO',  'Automotive',                       'Автомобильная промышленность',       'Avtomobil sanoati'),
  ('CNST',  'Construction & building materials','Строительство и стройматериалы',     'Qurilish va qurilish materiallari'),
  ('ENRG',  'Energy & utilities',               'Энергетика и коммунальные услуги',   'Energetika va kommunal xizmatlar'),
  ('OILG',  'Oil & gas',                        'Нефть и газ',                        'Neft va gaz'),
  ('TRAN',  'Transportation & logistics',       'Транспорт и логистика',              'Transport va logistika'),
  ('WHTR',  'Wholesale trade',                  'Оптовая торговля',                   'Ulgurji savdo'),
  ('RETL',  'Retail trade',                     'Розничная торговля',                 'Chakana savdo'),
  ('ICTS',  'IT & telecommunications',          'ИТ и телекоммуникации',              'AT va telekommunikatsiyalar'),
  ('PAPR',  'Paper & packaging',                'Бумага и упаковка',                  'Qog''oz va qadoqlash'),
  ('WOOD',  'Wood & furniture',                 'Дерево и мебель',                    'Yog''och va mebel'),
  ('PLST',  'Plastics & rubber',                'Пластмассы и резина',                'Plastmassa va kauchuk'),
  ('CONS',  'Consumer goods',                   'Потребительские товары',             'Iste''mol tovarlari'),
  ('SERV',  'Services',                         'Услуги',                             'Xizmatlar');

-- ---------------------------------------------------------------------------
-- Seed: countries (full ISO 3166-1 alpha-2 list)
-- ---------------------------------------------------------------------------
insert into tci.countries (code, name_en, name_ru, name_uz) values
  ('AD', 'Andorra', 'Андорра', 'Andorra'),
  ('AE', 'United Arab Emirates', 'Объединённые Арабские Эмираты', 'Birlashgan Arab Amirliklari'),
  ('AF', 'Afghanistan', 'Афганистан', 'Afg''oniston'),
  ('AG', 'Antigua and Barbuda', 'Антигуа и Барбуда', 'Antigua va Barbuda'),
  ('AI', 'Anguilla', 'Ангилья', 'Angilya'),
  ('AL', 'Albania', 'Албания', 'Albaniya'),
  ('AM', 'Armenia', 'Армения', 'Armaniston'),
  ('AO', 'Angola', 'Ангола', 'Angola'),
  ('AQ', 'Antarctica', 'Антарктида', 'Antarktida'),
  ('AR', 'Argentina', 'Аргентина', 'Argentina'),
  ('AS', 'American Samoa', 'Американское Самоа', 'Amerika Samoasi'),
  ('AT', 'Austria', 'Австрия', 'Avstriya'),
  ('AU', 'Australia', 'Австралия', 'Avstraliya'),
  ('AW', 'Aruba', 'Аруба', 'Aruba'),
  ('AX', 'Aland Islands', 'Аландские острова', 'Aland orollari'),
  ('AZ', 'Azerbaijan', 'Азербайджан', 'Ozarbayjon'),
  ('BA', 'Bosnia and Herzegovina', 'Босния и Герцеговина', 'Bosniya va Gertsegovina'),
  ('BB', 'Barbados', 'Барбадос', 'Barbados'),
  ('BD', 'Bangladesh', 'Бангладеш', 'Bangladesh'),
  ('BE', 'Belgium', 'Бельгия', 'Belgiya'),
  ('BF', 'Burkina Faso', 'Буркина-Фасо', 'Burkina-Faso'),
  ('BG', 'Bulgaria', 'Болгария', 'Bolgariya'),
  ('BH', 'Bahrain', 'Бахрейн', 'Bahrayn'),
  ('BI', 'Burundi', 'Бурунди', 'Burundi'),
  ('BJ', 'Benin', 'Бенин', 'Benin'),
  ('BL', 'Saint Barthelemy', 'Сен-Бартелеми', 'Sen-Bartelemi'),
  ('BM', 'Bermuda', 'Бермуды', 'Bermuda orollari'),
  ('BN', 'Brunei Darussalam', 'Бруней', 'Bruney'),
  ('BO', 'Bolivia', 'Боливия', 'Boliviya'),
  ('BQ', 'Bonaire, Sint Eustatius and Saba', 'Бонэйр, Синт-Эстатиус и Саба', 'Boneyr, Sint-Estatius va Saba'),
  ('BR', 'Brazil', 'Бразилия', 'Braziliya'),
  ('BS', 'Bahamas', 'Багамы', 'Bagama orollari'),
  ('BT', 'Bhutan', 'Бутан', 'Butan'),
  ('BV', 'Bouvet Island', 'Остров Буве', 'Buve oroli'),
  ('BW', 'Botswana', 'Ботсвана', 'Botsvana'),
  ('BY', 'Belarus', 'Беларусь', 'Belarus'),
  ('BZ', 'Belize', 'Белиз', 'Beliz'),
  ('CA', 'Canada', 'Канада', 'Kanada'),
  ('CC', 'Cocos (Keeling) Islands', 'Кокосовые острова', 'Kokos orollari'),
  ('CD', 'Congo, Democratic Republic of the', 'Демократическая Республика Конго', 'Kongo Demokratik Respublikasi'),
  ('CF', 'Central African Republic', 'Центральноафриканская Республика', 'Markaziy Afrika Respublikasi'),
  ('CG', 'Congo', 'Конго', 'Kongo'),
  ('CH', 'Switzerland', 'Швейцария', 'Shveytsariya'),
  ('CI', 'Cote d''Ivoire', 'Кот-д''Ивуар', 'Kot-d''Ivuar'),
  ('CK', 'Cook Islands', 'Острова Кука', 'Kuk orollari'),
  ('CL', 'Chile', 'Чили', 'Chili'),
  ('CM', 'Cameroon', 'Камерун', 'Kamerun'),
  ('CN', 'China', 'Китай', 'Xitoy'),
  ('CO', 'Colombia', 'Колумбия', 'Kolumbiya'),
  ('CR', 'Costa Rica', 'Коста-Рика', 'Kosta-Rika'),
  ('CU', 'Cuba', 'Куба', 'Kuba'),
  ('CV', 'Cabo Verde', 'Кабо-Верде', 'Kabo-Verde'),
  ('CW', 'Curacao', 'Кюрасао', 'Kyurasao'),
  ('CX', 'Christmas Island', 'Остров Рождества', 'Rojdestvo oroli'),
  ('CY', 'Cyprus', 'Кипр', 'Kipr'),
  ('CZ', 'Czechia', 'Чехия', 'Chexiya'),
  ('DE', 'Germany', 'Германия', 'Germaniya'),
  ('DJ', 'Djibouti', 'Джибути', 'Jibuti'),
  ('DK', 'Denmark', 'Дания', 'Daniya'),
  ('DM', 'Dominica', 'Доминика', 'Dominika'),
  ('DO', 'Dominican Republic', 'Доминиканская Республика', 'Dominikan Respublikasi'),
  ('DZ', 'Algeria', 'Алжир', 'Jazoir'),
  ('EC', 'Ecuador', 'Эквадор', 'Ekvador'),
  ('EE', 'Estonia', 'Эстония', 'Estoniya'),
  ('EG', 'Egypt', 'Египет', 'Misr'),
  ('EH', 'Western Sahara', 'Западная Сахара', 'G''arbiy Sahroi Kabir'),
  ('ER', 'Eritrea', 'Эритрея', 'Eritreya'),
  ('ES', 'Spain', 'Испания', 'Ispaniya'),
  ('ET', 'Ethiopia', 'Эфиопия', 'Efiopiya'),
  ('FI', 'Finland', 'Финляндия', 'Finlyandiya'),
  ('FJ', 'Fiji', 'Фиджи', 'Fiji'),
  ('FK', 'Falkland Islands', 'Фолклендские острова', 'Folklend orollari'),
  ('FM', 'Micronesia', 'Микронезия', 'Mikroneziya'),
  ('FO', 'Faroe Islands', 'Фарерские острова', 'Farer orollari'),
  ('FR', 'France', 'Франция', 'Fransiya'),
  ('GA', 'Gabon', 'Габон', 'Gabon'),
  ('GB', 'United Kingdom', 'Великобритания', 'Buyuk Britaniya'),
  ('GD', 'Grenada', 'Гренада', 'Grenada'),
  ('GE', 'Georgia', 'Грузия', 'Gruziya'),
  ('GF', 'French Guiana', 'Французская Гвиана', 'Fransuz Gvianasi'),
  ('GG', 'Guernsey', 'Гернси', 'Gernsi'),
  ('GH', 'Ghana', 'Гана', 'Gana'),
  ('GI', 'Gibraltar', 'Гибралтар', 'Gibraltar'),
  ('GL', 'Greenland', 'Гренландия', 'Grenlandiya'),
  ('GM', 'Gambia', 'Гамбия', 'Gambiya'),
  ('GN', 'Guinea', 'Гвинея', 'Gvineya'),
  ('GP', 'Guadeloupe', 'Гваделупа', 'Gvadelupa'),
  ('GQ', 'Equatorial Guinea', 'Экваториальная Гвинея', 'Ekvatorial Gvineya'),
  ('GR', 'Greece', 'Греция', 'Gretsiya'),
  ('GS', 'South Georgia and the South Sandwich Islands', 'Южная Георгия и Южные Сандвичевы острова', 'Janubiy Georgiya va Janubiy Sendvich orollari'),
  ('GT', 'Guatemala', 'Гватемала', 'Gvatemala'),
  ('GU', 'Guam', 'Гуам', 'Guam'),
  ('GW', 'Guinea-Bissau', 'Гвинея-Бисау', 'Gvineya-Bisau'),
  ('GY', 'Guyana', 'Гайана', 'Gayana'),
  ('HK', 'Hong Kong', 'Гонконг', 'Gonkong'),
  ('HM', 'Heard Island and McDonald Islands', 'Остров Херд и острова Макдональд', 'Xerd va Makdonald orollari'),
  ('HN', 'Honduras', 'Гондурас', 'Gonduras'),
  ('HR', 'Croatia', 'Хорватия', 'Xorvatiya'),
  ('HT', 'Haiti', 'Гаити', 'Gaiti'),
  ('HU', 'Hungary', 'Венгрия', 'Vengriya'),
  ('ID', 'Indonesia', 'Индонезия', 'Indoneziya'),
  ('IE', 'Ireland', 'Ирландия', 'Irlandiya'),
  ('IL', 'Israel', 'Израиль', 'Isroil'),
  ('IM', 'Isle of Man', 'Остров Мэн', 'Men oroli'),
  ('IN', 'India', 'Индия', 'Hindiston'),
  ('IO', 'British Indian Ocean Territory', 'Британская территория в Индийском океане', 'Britaniya Hind okeani hududi'),
  ('IQ', 'Iraq', 'Ирак', 'Iroq'),
  ('IR', 'Iran', 'Иран', 'Eron'),
  ('IS', 'Iceland', 'Исландия', 'Islandiya'),
  ('IT', 'Italy', 'Италия', 'Italiya'),
  ('JE', 'Jersey', 'Джерси', 'Jersi'),
  ('JM', 'Jamaica', 'Ямайка', 'Yamayka'),
  ('JO', 'Jordan', 'Иордания', 'Iordaniya'),
  ('JP', 'Japan', 'Япония', 'Yaponiya'),
  ('KE', 'Kenya', 'Кения', 'Keniya'),
  ('KG', 'Kyrgyzstan', 'Киргизия', 'Qirg''iziston'),
  ('KH', 'Cambodia', 'Камбоджа', 'Kambodja'),
  ('KI', 'Kiribati', 'Кирибати', 'Kiribati'),
  ('KM', 'Comoros', 'Коморы', 'Komor orollari'),
  ('KN', 'Saint Kitts and Nevis', 'Сент-Китс и Невис', 'Sent-Kits va Nevis'),
  ('KP', 'North Korea', 'КНДР', 'Shimoliy Koreya'),
  ('KR', 'South Korea', 'Республика Корея', 'Janubiy Koreya'),
  ('KW', 'Kuwait', 'Кувейт', 'Quvayt'),
  ('KY', 'Cayman Islands', 'Каймановы острова', 'Kayman orollari'),
  ('KZ', 'Kazakhstan', 'Казахстан', 'Qozog''iston'),
  ('LA', 'Laos', 'Лаос', 'Laos'),
  ('LB', 'Lebanon', 'Ливан', 'Livan'),
  ('LC', 'Saint Lucia', 'Сент-Люсия', 'Sent-Lyusiya'),
  ('LI', 'Liechtenstein', 'Лихтенштейн', 'Lixtenshteyn'),
  ('LK', 'Sri Lanka', 'Шри-Ланка', 'Shri-Lanka'),
  ('LR', 'Liberia', 'Либерия', 'Liberiya'),
  ('LS', 'Lesotho', 'Лесото', 'Lesoto'),
  ('LT', 'Lithuania', 'Литва', 'Litva'),
  ('LU', 'Luxembourg', 'Люксембург', 'Lyuksemburg'),
  ('LV', 'Latvia', 'Латвия', 'Latviya'),
  ('LY', 'Libya', 'Ливия', 'Liviya'),
  ('MA', 'Morocco', 'Марокко', 'Marokash'),
  ('MC', 'Monaco', 'Монако', 'Monako'),
  ('MD', 'Moldova', 'Молдова', 'Moldova'),
  ('ME', 'Montenegro', 'Черногория', 'Chernogoriya'),
  ('MF', 'Saint Martin (French part)', 'Сен-Мартен', 'Sen-Marten'),
  ('MG', 'Madagascar', 'Мадагаскар', 'Madagaskar'),
  ('MH', 'Marshall Islands', 'Маршалловы острова', 'Marshall orollari'),
  ('MK', 'North Macedonia', 'Северная Македония', 'Shimoliy Makedoniya'),
  ('ML', 'Mali', 'Мали', 'Mali'),
  ('MM', 'Myanmar', 'Мьянма', 'Myanma'),
  ('MN', 'Mongolia', 'Монголия', 'Mongoliya'),
  ('MO', 'Macao', 'Макао', 'Makao'),
  ('MP', 'Northern Mariana Islands', 'Северные Марианские острова', 'Shimoliy Mariana orollari'),
  ('MQ', 'Martinique', 'Мартиника', 'Martinika'),
  ('MR', 'Mauritania', 'Мавритания', 'Mavritaniya'),
  ('MS', 'Montserrat', 'Монтсеррат', 'Montserrat'),
  ('MT', 'Malta', 'Мальта', 'Malta'),
  ('MU', 'Mauritius', 'Маврикий', 'Mavrikiy'),
  ('MV', 'Maldives', 'Мальдивы', 'Maldiv orollari'),
  ('MW', 'Malawi', 'Малави', 'Malavi'),
  ('MX', 'Mexico', 'Мексика', 'Meksika'),
  ('MY', 'Malaysia', 'Малайзия', 'Malayziya'),
  ('MZ', 'Mozambique', 'Мозамбик', 'Mozambik'),
  ('NA', 'Namibia', 'Намибия', 'Namibiya'),
  ('NC', 'New Caledonia', 'Новая Каледония', 'Yangi Kaledoniya'),
  ('NE', 'Niger', 'Нигер', 'Niger'),
  ('NF', 'Norfolk Island', 'Остров Норфолк', 'Norfolk oroli'),
  ('NG', 'Nigeria', 'Нигерия', 'Nigeriya'),
  ('NI', 'Nicaragua', 'Никарагуа', 'Nikaragua'),
  ('NL', 'Netherlands', 'Нидерланды', 'Niderlandiya'),
  ('NO', 'Norway', 'Норвегия', 'Norvegiya'),
  ('NP', 'Nepal', 'Непал', 'Nepal'),
  ('NR', 'Nauru', 'Науру', 'Nauru'),
  ('NU', 'Niue', 'Ниуэ', 'Niue'),
  ('NZ', 'New Zealand', 'Новая Зеландия', 'Yangi Zelandiya'),
  ('OM', 'Oman', 'Оман', 'Ummon'),
  ('PA', 'Panama', 'Панама', 'Panama'),
  ('PE', 'Peru', 'Перу', 'Peru'),
  ('PF', 'French Polynesia', 'Французская Полинезия', 'Fransuz Polineziyasi'),
  ('PG', 'Papua New Guinea', 'Папуа — Новая Гвинея', 'Papua-Yangi Gvineya'),
  ('PH', 'Philippines', 'Филиппины', 'Filippin'),
  ('PK', 'Pakistan', 'Пакистан', 'Pokiston'),
  ('PL', 'Poland', 'Польша', 'Polsha'),
  ('PM', 'Saint Pierre and Miquelon', 'Сен-Пьер и Микелон', 'Sen-Pyer va Mikelon'),
  ('PN', 'Pitcairn', 'Питкэрн', 'Pitkern orollari'),
  ('PR', 'Puerto Rico', 'Пуэрто-Рико', 'Puerto-Riko'),
  ('PS', 'Palestine, State of', 'Палестина', 'Falastin'),
  ('PT', 'Portugal', 'Португалия', 'Portugaliya'),
  ('PW', 'Palau', 'Палау', 'Palau'),
  ('PY', 'Paraguay', 'Парагвай', 'Paragvay'),
  ('QA', 'Qatar', 'Катар', 'Qatar'),
  ('RE', 'Reunion', 'Реюньон', 'Reyunon'),
  ('RO', 'Romania', 'Румыния', 'Ruminiya'),
  ('RS', 'Serbia', 'Сербия', 'Serbiya'),
  ('RU', 'Russia', 'Россия', 'Rossiya'),
  ('RW', 'Rwanda', 'Руанда', 'Ruanda'),
  ('SA', 'Saudi Arabia', 'Саудовская Аравия', 'Saudiya Arabistoni'),
  ('SB', 'Solomon Islands', 'Соломоновы острова', 'Solomon orollari'),
  ('SC', 'Seychelles', 'Сейшелы', 'Seyshel orollari'),
  ('SD', 'Sudan', 'Судан', 'Sudan'),
  ('SE', 'Sweden', 'Швеция', 'Shvetsiya'),
  ('SG', 'Singapore', 'Сингапур', 'Singapur'),
  ('SH', 'Saint Helena, Ascension and Tristan da Cunha', 'Остров Святой Елены', 'Muqaddas Yelena oroli'),
  ('SI', 'Slovenia', 'Словения', 'Sloveniya'),
  ('SJ', 'Svalbard and Jan Mayen', 'Шпицберген и Ян-Майен', 'Shpitsbergen va Yan-Mayen'),
  ('SK', 'Slovakia', 'Словакия', 'Slovakiya'),
  ('SL', 'Sierra Leone', 'Сьерра-Леоне', 'Syerra-Leone'),
  ('SM', 'San Marino', 'Сан-Марино', 'San-Marino'),
  ('SN', 'Senegal', 'Сенегал', 'Senegal'),
  ('SO', 'Somalia', 'Сомали', 'Somali'),
  ('SR', 'Suriname', 'Суринам', 'Surinam'),
  ('SS', 'South Sudan', 'Южный Судан', 'Janubiy Sudan'),
  ('ST', 'Sao Tome and Principe', 'Сан-Томе и Принсипи', 'San-Tome va Prinsipi'),
  ('SV', 'El Salvador', 'Сальвадор', 'Salvador'),
  ('SX', 'Sint Maarten (Dutch part)', 'Синт-Мартен', 'Sint-Marten'),
  ('SY', 'Syria', 'Сирия', 'Suriya'),
  ('SZ', 'Eswatini', 'Эсватини', 'Esvatini'),
  ('TC', 'Turks and Caicos Islands', 'Тёркс и Кайкос', 'Terks va Kaykos orollari'),
  ('TD', 'Chad', 'Чад', 'Chad'),
  ('TF', 'French Southern Territories', 'Французские Южные территории', 'Fransuz Janubiy hududlari'),
  ('TG', 'Togo', 'Того', 'Togo'),
  ('TH', 'Thailand', 'Таиланд', 'Tailand'),
  ('TJ', 'Tajikistan', 'Таджикистан', 'Tojikiston'),
  ('TK', 'Tokelau', 'Токелау', 'Tokelau'),
  ('TL', 'Timor-Leste', 'Восточный Тимор', 'Sharqiy Timor'),
  ('TM', 'Turkmenistan', 'Туркменистан', 'Turkmaniston'),
  ('TN', 'Tunisia', 'Тунис', 'Tunis'),
  ('TO', 'Tonga', 'Тонга', 'Tonga'),
  ('TR', 'Turkiye', 'Турция', 'Turkiya'),
  ('TT', 'Trinidad and Tobago', 'Тринидад и Тобаго', 'Trinidad va Tobago'),
  ('TV', 'Tuvalu', 'Тувалу', 'Tuvalu'),
  ('TW', 'Taiwan', 'Тайвань', 'Tayvan'),
  ('TZ', 'Tanzania', 'Танзания', 'Tanzaniya'),
  ('UA', 'Ukraine', 'Украина', 'Ukraina'),
  ('UG', 'Uganda', 'Уганда', 'Uganda'),
  ('UM', 'United States Minor Outlying Islands', 'Внешние малые острова США', 'AQSh tashqi kichik orollari'),
  ('US', 'United States', 'США', 'Amerika Qo''shma Shtatlari'),
  ('UY', 'Uruguay', 'Уругвай', 'Urugvay'),
  ('UZ', 'Uzbekistan', 'Узбекистан', 'O''zbekiston'),
  ('VA', 'Holy See (Vatican)', 'Ватикан', 'Vatikan'),
  ('VC', 'Saint Vincent and the Grenadines', 'Сент-Винсент и Гренадины', 'Sent-Vinsent va Grenadin'),
  ('VE', 'Venezuela', 'Венесуэла', 'Venesuela'),
  ('VG', 'Virgin Islands (British)', 'Виргинские острова (Британские)', 'Britaniya Virgin orollari'),
  ('VI', 'Virgin Islands (U.S.)', 'Виргинские острова (США)', 'AQSh Virgin orollari'),
  ('VN', 'Vietnam', 'Вьетнам', 'Vyetnam'),
  ('VU', 'Vanuatu', 'Вануату', 'Vanuatu'),
  ('WF', 'Wallis and Futuna', 'Уоллис и Футуна', 'Uollis va Futuna'),
  ('WS', 'Samoa', 'Самоа', 'Samoa'),
  ('YE', 'Yemen', 'Йемен', 'Yaman'),
  ('YT', 'Mayotte', 'Майотта', 'Mayotta'),
  ('ZA', 'South Africa', 'ЮАР', 'Janubiy Afrika Respublikasi'),
  ('ZM', 'Zambia', 'Замбия', 'Zambiya'),
  ('ZW', 'Zimbabwe', 'Зимбабве', 'Zimbabve');
